---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "rseqc_genebodycoverage"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::rseqc=5.0.3"
