# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "parse_xlsx"
## TODO nf-core: Add a description of the subworkflow and list keywords
description: Parse xlsx file to make samplesheet.csv
keywords:
  - parse
  - xlsx
  - csv
  - yaml
## TODO nf-core: Add a list of the modules and/or subworkflows used in the subworkflow
components:
  - parsexlsx/samples
  - parsexlsx/concs
  - parsexlsx/customer
  - parsexlsx/experiments
  - parsexlsx/organism
## TODO nf-core: List all of the channels used as input with a description and their structure
input:
  - ch_xlsx:
      type: file
      description: |
        Channel containing xlsx file
        Structure: [ path(xlsx) ]
      pattern: "*.xlsx"
## TODO nf-core: List all of the channels used as output with a descriptions and their structure
output:
  - samples:
      type: file
      description: |
        Channel containing csv file
        Structure: [ path(samples) ]
      pattern: "*.csv"
  - concs:
      type: file
      description: |
        Channel containing  (BAI) files
        Structure: [ path(concs) ]
      pattern: "*.csv"
  - informations:
      type: file
      description: |
        Channel containing CSI files
        Structure: [ path(yml) ]
      pattern: "*.yml"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@iyamaguchi"
maintainers:
  - "@iyamaguchi"
